In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
element = arr_1d[2]
print(element)

3


In [5]:
row = arr_2d[1]
print(row)

[4 5 6]


In [6]:
specific_element = arr_2d[0,2]
print(specific_element)

3


In [8]:
subarray = arr_1d[1:4]
print(subarray)

[2 3 4]


In [9]:
reshaped_arr = arr_1d.reshape((5,1))
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
flattened_arr = arr_2d.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


In [11]:
concatenated_arr = np.concatenate([arr_1d,arr_1d])
print(concatenated_arr)

[1 2 3 4 5 1 2 3 4 5]


In [13]:
concatenated_arr_2d = np.concatenate([arr_2d,arr_2d], axis = 1)
print(concatenated_arr_2d)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [14]:
split_arr = np.split(arr_1d, 5)
print(split_arr)

[array([1]), array([2]), array([3]), array([4]), array([5])]


In [15]:
split_arr_2d = np.split(arr_2d,2,axis = 0)
print(split_arr_2d)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [16]:
transposed_arr = arr_2d.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [17]:
addition = arr_1d + 2
print(addition)

[3 4 5 6 7]


In [18]:
multiplication = arr_2d * 2
print(multiplication)

[[ 2  4  6]
 [ 8 10 12]]


In [20]:
#sort 1d array in ascending order
sorted_arr = np.sort(arr_1d)
print(sorted_arr)

[1 2 3 4 5]


In [21]:
sorted_arr_2d = np.sort(arr_2d, axis=0)
print(sorted_arr_2d)

[[1 2 3]
 [4 5 6]]


In [22]:
sorted_arr_2d_column = arr_2d[arr_2d[:,1].argsort()]
print(sorted_arr_2d_column)

[[1 2 3]
 [4 5 6]]


In [23]:
mask = arr_2d > 3
print(mask)

[[False False False]
 [ True  True  True]]


In [24]:
filtered_arr = arr_2d[mask]
print(filtered_arr)

[4 5 6]


In [25]:
arr_2d[mask] = 0
print(arr_2d)

[[1 2 3]
 [0 0 0]]


In [26]:
hstacked_arr = np.hstack([arr_2d, arr_2d])
print(hstacked_arr)

[[1 2 3 1 2 3]
 [0 0 0 0 0 0]]


In [27]:
vstacked_arr = np.vstack([arr_2d,arr_2d])
print(vstacked_arr)

[[1 2 3]
 [0 0 0]
 [1 2 3]
 [0 0 0]]
