In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
element = arr_1d[2]
print(element)

3


In [5]:
row = arr_2d[1]
print(row)

[4 5 6]


In [6]:
specific_element = arr_2d[0,2]
print(specific_element)

3


In [8]:
subarray = arr_1d[1:4]
print(subarray)

[2 3 4]
